### ISSUE TITLE
app-pipeline "Dev - Build Image" needs option for insecure registry push

### ISSUE THREAD

**Issue by thomasmckay** [RHsyseng/jenkins-on-openshift#92]
The registry specified in _group_vars/all.yml_ as _central_registry_hostname_ needs an insecure option or the build will fail in this case.

If this is meant to be the internal registry then perhaps should default to the ip address and port? Having insecure option for this would still be useful when customizing setup.

```
[logs:build/nodejs-mongo-persistent-1] Pushing image docker-registry.192.168.42.213.nip.io/registry/nodejs-mongo-persistent:1.0-1 ...
[logs:build/nodejs-mongo-persistent-1] error: build error: Failed to push image: Get https://docker-registry.192.168.42.213.nip.io/v1/_ping: x509: certificate signed by unknown authority
[logs:build/nodejs-mongo-persistent-1] 
```

**Comment by jcpowermac** [comment]
@thomasmckay I ran into this as well with `oc cluster up`.  The ImageStream is already configured for insecure - which apparently is ignored.  In a OCP multinode cluster all I needed to do was add the certificate to `/etc/docker/certs.d`.  In `oc cluster up` v3.7.0 RC0 it requires additional steps:

1. Add the certificate to `/etc/pki/ca-trust/source/anchors`
```
/etc/pki/ca-trust/source/anchors             
└── registry.crt      
```
2. `update-ca-trust extract`

3. Add certificate under `/etc/docker/certs.d`
```
/etc/docker/certs.d/docker-registry-default.apps.registry-cluster.virtomation.com
└── ca.crt
```
4. Modify `/var/lib/origin/openshift.local.config/master/master-config.yaml`
```
imagePolicyConfig:
  allowedRegistriesForImport:
  - domainName: docker.io
  - domainName: '*.docker.io'
  - domainName: '*.redhat.com'
  - domainName: gcr.io
  - domainName: quay.io
  - domainName: '*.amazonaws.com'
  - domainName: '*.virtomation.com'
  - domainName: 'docker-registry-default.apps.registry-cluster.virtomation.com:80'
```
5. Reboot
6. Run with existing config option e.g. `oc cluster up --public-hostname="10.53.252.73.nip.io" --routing-suffix="apps.10.53.252.73.nip.io" --use-existing-config`
